### ISSUE TITLE
디렉토리 구조

### ISSUE THREAD

**Issue by laggu** [Beyond-Imagination/express-boilerplate#18]
## 개요
기본적인 디렉토리 구조를 결정

env
src
| - controllers
| - services
| - middlewares
| - models
| - utils
| - errors
| - types
| - libs
| - interfaces
| - routes
| - loaders
| - app.ts

**Comment by laggu** [comment]
@SimDaSong @inhobaek 디렉토리 구조를 먼저 이야기 하면 좋을것 같아요.
제가 간단히 적었는데 더 필요하다고 생각하는 부분이 있으면 말씀 부탁드립니다

**Comment by SimDaSong** [comment]
1. authentications에는 어떤 파일들이 들어가나요?
2. libs, helpers 폴더도 추가하면 좋을 것 같습니다 (https://github.com/erikras/react-redux-universal-hot-example/issues/808)
```
/helpers is more of a place where you store code architectural snippets in my view. Things essential for bootstrapping components and developer ergonomics.
/utils is a place where you can place small snippets you can use throughout the application. Small functions to build bigger things with.
/utils has very short and specific functions used throughout functions in /libs
/libs holds the individual steps a given module calls
```
3. routes, interfaces 폴더도 있으면 좋을 거 같아용
routes: router 분리
interfaces: typescript interface들을 모아둠
4. 지금 시도 중인건데, 기존 환경 변수 관리하는 방식이 너무 복잡하고 할 것도 많아서 https://github.com/santiq/bulletproof-nodejs, https://github.com/w3tecch/express-typescript-boilerplate/ 레포지토리 참고해서 환경변수 관리하는 방식을 바꿀까 합니다. 이렇게 하면 src/config 폴더가 아니라 /env 폴더가 필요할 거 같아요! (안에 있는 내용도 다른데 저희끼리 얘기 나눌 때 더 자세하게 설명할게요)
5. 그리고 app.ts 파일 내에 있는 내용들을 분리해서 loaders 폴더 내 파일들로 분리하고 그걸 app.ts에서 호출만 하는 방식으로 옮기는 방식이 좋지 않을까 생각하고 있습니다! 그렇게 되면 mmt-server 내 plugins 폴더랑 그 안에 있는 내용도 loaders 폴더로 옮기고 app.ts 파일 내에서 loaders를 일괄적으로 호출해주면 더 깔끔하고 유지보수가 쉬운 코드가 될 것 같습니다. 이 방식도 https://github.com/santiq/bulletproof-nodejs, https://github.com/w3tecch/express-typescript-boilerplate/ 를 참고했어요!

결론
```
| - env
| - src
    | - controllers
    | - services
    | - routes
    | - middlewares
    | - models
    | - utils
    | - helpers
    | - libs
    | - errors
    | - types
    | - interfaces
    | - loaders
    | - authentications
```

**Comment by SimDaSong** [comment]
@laggu @inhobaek 이거 일단 close 처리 해도 될까요?

**Comment by laggu** [comment]
> @laggu @inhobaek 이거 일단 close 처리 해도 될까요?

네네 좋아요
