### ISSUE TITLE
코드 머지 방식

### ISSUE THREAD

**Issue by laggu** [Beyond-Imagination/express-boilerplate#22]
코드를 Push 하는 방식이 아닌 pull request 를 이용해 merge 하는 방식을 사용하고자 합니다.

현재 최소 1명의 approve 를 받아야 하도록 설정하였는데
이 설정이 괜찮을지 의견 부탁드립니다

**Comment by laggu** [comment]
@inhobaek @SimDaSong

**Comment by SimDaSong** [comment]
넵 저는 좋은 것 같습니다!
