### ISSUE TITLE
loader 의 존재 목적

### ISSUE THREAD

**Issue by laggu** [Beyond-Imagination/express-boilerplate#64]
현 loader 디렉토리 내의 initialize 하는 코드들을 몰아넣은 이유가 궁금합니다

aws, passport, mongoose, env 등의 코드가 초기화 부분과 실제 동작 부분의 코드가 분리되는데 이런 구조의 장점이 무엇인가요

**Comment by laggu** [comment]
@SimDaSong @inhobaek @truly-sparkle 다른분들은 의견 어떠신가요??

**Comment by inhobaek** [comment]
> 현 loader 디렉토리 내의 initialize 하는 코드들을 몰아넣은 이유가 궁금합니다
> aws, passport, mongoose, env 등의 코드가 초기화 부분과 실제 동작 부분의 코드가 분리되는데 이런 구조의 장점이 무엇인가요

제가 생각하기로는 콘텐츠 단위로 코드를 구분하기 보다, 행위에 초점을 맞춰서 구분을 하려고해서 `/loader/` 하위에 모아놓은 것 같습니다.
애플리케이션에서 처음 기동하고 동작하는데 필요한 코드를 하나의 디렉토리 모아서 보기위함이 아닐까 추측됩니다.
configuration, utils 같은 역할을 하는 것도 도메인 구분없이 모아놓는 편이라 그런 것 같네요.

뒤에 말씀주신 것처럼 각 콘텐츠 별로 구분하고 각각의 폴더 하위에서 `/passport/init`, `/aws/init` 이러는 것과 `/loader/aws`, `/loader/passport` 하는 것이 특별히 차이나는 지점은 모르겠네요.
성능 상의 문제라기보단 참조할 때 경로로 인해 코드 작성의 편의성이 달라질 것 같습니다. 

#68 PR 보다가 문득 생각나서 답변 드립니다.

**Comment by laggu** [comment]
> 제가 생각하기로는 콘텐츠, 주제 단위로 코드를 구분하기 보다, 행위에 초점을 맞춰서 구분을 하려고해서 `/loader/` 하위에 모아놓은 것 같습니다. 애플리케이션에서 처음 기동하고 동작하는데 필요한 코드를 하나의 디렉토리 모아서 보기위함이 아닐까 추측됩니다. configuration, utils 같은 역할을 하는 것도 주제 구분없이 모아놓는 편이라 그런 것 같네요.
> 
> 뒤에 말씀주신 것처럼 각 콘텐츠, 주제 별로 구분하고 각각의 폴더 하위에서 `/passport/init`, `/aws/init` 이러는 것과 `/loader/aws`, `/loader/passport` 하는 것이 특별히 차이나는 지점은 모르겠네요. 성능 상의 문제라기보단 참조할 때 경로로 인해 코드 작성의 편의성이 달라질 것 같습니다.
> 
> #68 PR 보다가 문득 생각나서 답변 드립니다.

저도 사실 비슷하게 생각해요 성능상의 문제는 없어 보이고 편의성의 문제인거 같은데 
지금 구조가 더 편리하다고 판단했던 이유가 어떤건지 궁금했습니다

**Comment by truly-sparkle** [comment]
저도 같이 변경되는 확률이 높은 코드끼리 묶어놓는게 좋을 것 같습니다!
